### ISSUE TITLE
Not shown from Preference Fragment 

### ISSUE THREAD

**Issue by jpshelley** [MrEngineer13/SnackBar#38]
If I'm using a standard activity that hosts a PreferenceFragment, the snackbar is not shown.

1) Creating the Snackbar in the activity, not the fragment.
2) Showing the Snackbar from the activity, after fragment issues the command.

Thoughts?

**Comment by MrEngineer13** [comment]
Are you using the Fragment or Activity to build the SnackBar?

**Comment by jpshelley** [comment]
@MrEngineer13 In the Activity that is hosting a PreferenceFragment.

**Comment by MrEngineer13** [comment]
I'm going to close this as there haven't been any updates however if you do feel free to explain how you got it working.
