### ISSUE TITLE
Snackbar not show when rotating screen

### ISSUE THREAD

**Issue by TriPSs** [MrEngineer13/SnackBar#46]
After i rotate the screen the snackbar wond't show any more.
Ik trayed it with the onSaveInstanceState but it does't work.

How can i solve dis? am i doing somting wrong?

**Comment by SuperAwesomeness** [comment]
The issue has not been fixed. Why did you close it?

**Comment by CoolMind** [comment]
@SuperAwesomeness, because he doesn't know, how to fix.
