### ISSUE TITLE
Callback Once Snackbar Disappears

### ISSUE THREAD

**Issue by arayray** [MrEngineer13/SnackBar#56]
I'm not sure if this exists currently or not but a good feature would be a callback so when the dialog disappears you can run a function. Prefect for any undo button, simply don't do anything until the callback is called.

**Comment by MrEngineer13** [comment]
There's already a built in method to do this. Just set a OnVisibiltyChangeListener like so:

	.withVisibilityChangeListener(new SnackBar.OnVisibilityChangeListener() {
			@Override
			public void onShow(int stackSize) {
				Log.i("SNACKBAR", "onShow Snacks left to show: "+stackSize);
			}

			@Override
			public void onHide(int stackSize) {
				Log.i("SNACKBAR", "onHide Snacks left to show: "+stackSize);
			}
	})
