### ISSUE TITLE
Transparent nav bar

### ISSUE THREAD

**Issue by 92jacko** [MrEngineer13/SnackBar#59]
When using KK+ transparent styles, the SnackBar appears behind the nav bar.

Either bottom padding or a bottom margin would be nice to make the resting position above the nav bar.

Great library!

**Comment by MrEngineer13** [comment]
An easy way to deal with this is to create a layout with your required bottom margin then just build your SnackBar into that layout. For example if your layout was called `margin_snackbar` here's how to build the SnackBar into it: 

    new SnackBar.Builder(getActivity().getApplicationContext(), root.findViewById(R.id.margin_snackbar))
        .withOnClickListener(this)
        .withMessage("This library is awesome!") // OR
        .withMessageId(messageId)

        .withActionMessage("Action") // OR
        .withActionMessageId(actionMsgId)

        .withTextColorId(textColorId)
        .withVisibilityChangeListener(this)
        .withStyle(style)
        .withDuration(duration)
        .show();
