### ISSUE TITLE
Style?

### ISSUE THREAD

**Issue by crysan** [MrEngineer13/SnackBar#73]
Hi! 
I use this:

        new SnackBar.Builder(this)
                .withMessageId(R.string.title_on)
                .withStyle(SnackBar.Style.INFO)
                .withDuration(SnackBar.SHORT_SNACK)
                .show();

Unfortunately, no style is not changed. As displayed by default, and displays in all directions of style.

**Comment by nhojyer07** [comment]
It is used for the button color, and not the background.

**Comment by crysan** [comment]
You 've been told that the problem is already solved itself. Thank you!
