### ISSUE TITLE
onShow onHide listener

### ISSUE THREAD

**Issue by alorma** [MrEngineer13/SnackBar#74]
Hi.

I need to modify the UI when the snackbar is shown.

![Default UI](https://cloud.githubusercontent.com/assets/887462/6526732/64af2e30-c415-11e4-8fde-12caf53378a7.jpg)
![UI with Snackbar](https://cloud.githubusercontent.com/assets/887462/6526738/6b5ff642-c415-11e4-9b3f-9676542aa36e.jpg)

But now the SnackBar is shown above the Button
![Button behind](https://cloud.githubusercontent.com/assets/887462/6526762/9194e962-c415-11e4-80ce-361ebf20ac7b.png)

How can I achieve this with this library?

**Comment by taufan20** [comment]
you can implement withVisibilityChangeListener(); in your SnackBar. here is mine using floating action button:

<pre>
new SnackBar.Builder(ActivityHome.this)
                    .withMessage(getString(R.string.distance_alert))
                    .withVisibilityChangeListener(new SnackBar.OnVisibilityChangeListener() {
                        @Override
                        public void onShow(int i) {
                            ViewPropertyAnimator.animate(mFabLocation).cancel();
                      ViewPropertyAnimator.animate(mFabLocation).translationY(-72).setDuration(200).start();
                        }

                        @Override
                        public void onHide(int i) {
                            ViewPropertyAnimator.animate(mFabLocation).cancel();
                         ViewPropertyAnimator.animate(mFabLocation).translationY(0).setDuration(200).start();
                        }
                    })
                    .show();
</pre>
