### ISSUE TITLE
Reset duration

### ISSUE THREAD

**Issue by alorma** [MrEngineer13/SnackBar#76]
Hi.

I'm in the case that i need to rest the duration, because i show one SnackBar and before it dismiss i will show again if not exist, or let SnackBar to stay in the screen the duration time agian.

Can it be implemented?

SnackBar,resetProgress()

?

Is ok if i try to do a PR?

**Comment by MrEngineer13** [comment]
Yea, PRs are welcome, as long as you do them on the `dev` branch as opposed to on `master`
