### ISSUE TITLE
SnackBar dismiss when swipe from top

### ISSUE THREAD

**Issue by alorma** [MrEngineer13/SnackBar#83]
Hi.

When we swipe from top of the SnackBar, it hides to the bottom, and we need to relaunch.

But without a listener or method to cancel that

**Comment by MrEngineer13** [comment]
Are you asking how to make the snackbar show for an indefinite amount of time?

**Comment by alorma** [comment]
No, i say that if you do a "swipe" from top, notification is disapeear, and is never shown again.

What i say with swipe, is touch on the top and drag to bottom
